services:
  frontend:
    build:
      context: ./frontend
    container_name: service_deskai_front
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: service_deskai_back
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: service_deskai_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
